8-do-nenemddin/DECASE-BE

.env.properties
.gitignore
src/main/java/com/skala/decase/domain/document/domain/Document.java
src/main/java/com/skala/decase/domain/project/controller/ProjectController.java
src/main/java/com/skala/decase/domain/project/controller/dto/response/EditProjectResponseDto.java
src/main/java/com/skala/decase/domain/project/domain/Project.java
src/main/java/com/skala/decase/domain/project/service/ProjectService.java
src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/RequirementDto.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/RequirementRevisionDto.java
src/main/java/com/skala/decase/domain/requirement/domain/Requirement.java
src/main/java/com/skala/decase/domain/requirement/repository/RequirementRepository.java
src/main/java/com/skala/decase/domain/requirement/service/RepositoryService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
src/main/resources/application-local.yml
src/main/resources/application.yml

- 프로젝트 수정
- 프로젝트 삭제
- close #19 
N/A
N/A

Feat/project : 프로젝트 관리 관련 로직 개발

---

src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/CreateRequirementDto.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/UpdateRequirementDto.java
src/main/java/com/skala/decase/domain/requirement/domain/Requirement.java
src/main/java/com/skala/decase/domain/requirement/domain/RequirementDocument.java
src/main/java/com/skala/decase/domain/requirement/exception/RequirementException.java
src/main/java/com/skala/decase/domain/requirement/repository/RequirementDocumentRepository.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java

요구사항 셀 수정 및 삭제 로직 생성
- close #21 
N/A
N/A

feat : 요구사항 수정/삭제 로직 생성

---

src/main/java/com/skala/decase/domain/project/controller/ProjectController.java
src/main/java/com/skala/decase/domain/project/controller/dto/response/ProjectDetailResponseDto.java
src/main/java/com/skala/decase/domain/project/service/ProjectService.java

단일 프로젝트 조회를 위한 api 개발
- close #31 
N/A
N/A

feat: 단일 프로젝트 조회 api 추가

---

build.gradle
src/main/java/com/skala/decase/domain/project/controller/ProjectController.java
src/main/java/com/skala/decase/domain/project/controller/dto/response/MappingTableResponseDto.java
src/main/java/com/skala/decase/domain/project/service/ProjectService.java

조견표 생성 로직 작성
- close #36 
N/A
N/A

feat: 조견표 생성

---

src/main/java/com/skala/decase/domain/project/controller/ProjectMemberController.java
src/main/java/com/skala/decase/domain/project/controller/dto/response/InvitationInfoResponse.java
src/main/java/com/skala/decase/domain/project/mapper/ProjectMemberMapper.java
src/main/java/com/skala/decase/domain/project/service/MailService.java
src/main/java/com/skala/decase/domain/project/service/ProjectInvitationService.java

피곤해서 나중에 적을게유 .............................................................. ❤️ 
- close #이슈번호

Feat/memberProject: 피곤해서 나중에 적을게유 .............................................................. ❤️ 

---

build.gradle
src/main/java/com/skala/decase/domain/document/controller/AsIsController.java
src/main/java/com/skala/decase/domain/document/controller/DocumentController.java
src/main/java/com/skala/decase/domain/document/controller/DocumentPreviewController.java
src/main/java/com/skala/decase/domain/document/controller/dto/DocumentDetailResponse.java
src/main/java/com/skala/decase/domain/document/controller/dto/DocumentPreviewDto.java
src/main/java/com/skala/decase/domain/document/domain/Document.java
src/main/java/com/skala/decase/domain/document/mapper/DocumentMapper.java
src/main/java/com/skala/decase/domain/document/repository/DocumentRepository.java
src/main/java/com/skala/decase/domain/document/service/AsisService.java
src/main/java/com/skala/decase/domain/document/service/DocumentPreviewService.java
src/main/java/com/skala/decase/domain/document/service/DocumentService.java
src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
src/main/java/com/skala/decase/domain/requirement/controller/RfpProcessingController.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/UpdateRequirementDto.java
src/main/java/com/skala/decase/domain/requirement/mapper/RequirementServiceMapper.java
src/main/java/com/skala/decase/domain/requirement/repository/RequirementRepository.java
src/main/java/com/skala/decase/domain/requirement/service/AsyncRfpProcessor.java
src/main/java/com/skala/decase/domain/requirement/service/ExelExportService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
src/main/java/com/skala/decase/domain/requirement/service/RfpProcessingService.java
src/main/java/com/skala/decase/domain/requirement/service/SRSUpdateService.java
src/main/java/com/skala/decase/domain/source/service/SourceRepository.java
src/main/java/com/skala/decase/global/config/AsyncConfig.java

- 프론트랑 연결하면서 생긴 문제들 해결
- 요구사항 정의서 생성 시 As is 문서 생성 병렬 처리 actuator 추가
- [ x ] 기능 개발
#38 

feat: 파일 미리보기, 요구사항 정의서 api 수정

---

src/main/java/com/skala/decase/domain/project/controller/ProjectController.java
src/main/java/com/skala/decase/domain/project/controller/ProjectInvitationController.java
src/main/java/com/skala/decase/domain/project/controller/dto/response/DeleteProjectResponse.java
src/main/java/com/skala/decase/domain/project/domain/Project.java
src/main/java/com/skala/decase/domain/project/mapper/ProjectInvitationMapper.java
src/main/java/com/skala/decase/domain/project/mapper/ProjectMapper.java
src/main/java/com/skala/decase/domain/project/mapper/SuccessMapper.java
src/main/java/com/skala/decase/domain/project/service/ProjectInvitationService.java
src/main/java/com/skala/decase/domain/project/service/ProjectService.java

- 입출력 형식에 맞게 메서드 수정
- ProjectMember -> ProjectInvitation으로 변경
- close #45

Refactor: 코드 수정 및 컨트롤러명 변경

---

src/main/java/com/skala/decase/domain/member/controller/MemberProjectController.java
src/main/java/com/skala/decase/domain/member/service/MemberProjectService.java
src/main/java/com/skala/decase/domain/project/service/ProjectInvitationService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java

Refactor: 전체 코드 수정

---

src/main/java/com/skala/decase/domain/mockup/controller/MockupController.java
src/main/java/com/skala/decase/domain/mockup/controller/dto/response/CreateMockUpRequest.java
src/main/java/com/skala/decase/domain/mockup/mapper/MockupMapper.java
src/main/java/com/skala/decase/domain/mockup/service/CreateMockupService.java
src/main/java/com/skala/decase/domain/mockup/service/MockupAsyncService.java
src/main/java/com/skala/decase/global/config/AsyncConfig.java

목업 생성 fast api 연결
- [ x ] 기능 개발
- #47 

feat: 목업 생성 fast api 연결

---

build.gradle
src/main/java/com/skala/decase/DecaseApplication.java
src/main/java/com/skala/decase/domain/project/service/MailService.java

메일 연속 전송 가능하도록 종속성 및 코드 추가
- close #49

fix: 메일 연속 전송 가능 하도록 수정

---

src/main/java/com/skala/decase/domain/mockup/controller/MockupController.java
src/main/java/com/skala/decase/domain/mockup/domain/dto/MockupExistDto.java
src/main/java/com/skala/decase/domain/mockup/service/MockupService.java

목업 존재 확인 api 수정

---

src/main/java/com/skala/decase/domain/requirement/domain/PendingRequirement.java
src/main/java/com/skala/decase/domain/requirement/service/PendingRequirementService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java

feat : 요구사항 수정 요청 api 수정

---

src/main/resources/application.yml

docs: base line 추가

---

src/main/java/com/skala/decase/domain/document/service/DocumentService.java

chore : 사용자 문서 업로드 시 프로젝트 리비전 증가

---

src/main/resources/application.yml

docs: deploy 수정

---

src/main/java/com/skala/decase/domain/member/domain/Member.java
src/main/java/com/skala/decase/domain/member/repository/MemberProjectRepository.java
src/main/java/com/skala/decase/domain/member/service/AuthService.java
src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/request/DeleteRequestDto.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/RequirementDto.java
src/main/java/com/skala/decase/domain/requirement/domain/PendingRequirement.java
src/main/java/com/skala/decase/domain/requirement/domain/Requirement.java
src/main/java/com/skala/decase/domain/requirement/service/PendingRequirementService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
src/main/java/com/skala/decase/global/config/CorsConfig.java

개별 요구사항 삭제 요청 및 삭제 승인
어드민인 경우 탈퇴 제한

feat : 개별 요구사항 삭제 로직 추가

---

src/main/java/com/skala/decase/domain/document/mapper/DocumentMapper.java
src/main/java/com/skala/decase/domain/document/service/DocumentPreviewService.java
src/main/java/com/skala/decase/domain/document/service/DocumentService.java

Chore: docs api 수정

---

src/main/java/com/skala/decase/domain/mockup/controller/dto/request/CreateMockUpRequest.java
src/main/java/com/skala/decase/domain/mockup/controller/dto/request/CreateMockUpSourceRequest.java
src/main/java/com/skala/decase/domain/mockup/mapper/MockupMapper.java
src/main/java/com/skala/decase/domain/mockup/service/CreateMockupService.java
src/main/java/com/skala/decase/domain/requirement/controller/SrsCallbackController.java
src/main/java/com/skala/decase/domain/requirement/controller/SrsProcessingController.java
src/main/java/com/skala/decase/domain/requirement/service/SrsProcessingService.java
src/main/java/com/skala/decase/domain/requirement/service/SrsProcessor.java
src/main/resources/application-local.yml
src/main/resources/application.yml

- asis 분석 결과 콜백 형식으로 받아오게 수정
- 목업 생성 요청 dto AI 쪽에 맞춰서 수정
- 폴더 경로 hostPath에 맞춰서 수정
- [ X ] 기능 개발
- close #이슈번호

fix: asis 분석 결과 콜백 형식으로 받아오게 수정

---

src/main/resources/application-local.yml
src/main/resources/application-prod.yml

feat: audit 설정 추가

---

src/main/java/com/skala/decase/global/config/DBInitializer.java

feat: source_id dbinitializer 추가

---

src/main/java/com/skala/decase/global/config/DBInitializer.java

feat: auto increment 세팅 확인 추가

---

k8s/deploy.yaml

feat: 파일 스토리지 생성 deploy.yaml수정

---

src/main/java/com/skala/decase/domain/requirement/service/SrsProcessingService.java
src/main/java/com/skala/decase/global/config/DBInitializer.java

asis 분석 상태 저장 로직 COMPLETE 수신 시 저장

---

src/main/java/com/skala/decase/domain/requirement/service/SrsProcessingService.java

fix: asis 분석 상태 PROCESSING, COMPLETED 일때 저장

---

k8s/deploy.yaml

feat: -Djava.awt.headless=true 추가

---

k8s/deploy.yaml
src/main/java/com/skala/decase/DecaseApplication.java
src/main/resources/application.yml

docs: 엑셀 설정 추가

---

.github/workflows/ci-cd.yaml

feat: cicd.yaml 추가

---

src/main/java/com/skala/decase/domain/project/service/MailService.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

fix: 프로젝트 초대 url 수정

---

src/main/java/com/skala/decase/domain/requirement/controller/SrsProcessingController.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

feat: srs-update callback url 추가

---

src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/SourceResponse.java
src/main/java/com/skala/decase/domain/requirement/mapper/RequirementServiceMapper.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java

요구사항 검색 수정

---

src/main/java/com/skala/decase/domain/mockup/service/MockupService.java

feat: 화면 정의서 미리보기 시 .png 파일 반환 추가

---

src/main/java/com/skala/decase/domain/mockup/service/MockupService.java

feat: 목업 다운로드 시 png 파일도 다운로드

---

build.gradle
src/main/java/com/skala/decase/domain/document/domain/Document.java
src/main/java/com/skala/decase/domain/project/domain/ProjectInvitation.java
src/main/java/com/skala/decase/domain/requirement/controller/RequirementController.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/request/UpdateRequirementDto.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/RequirementAuditResponse.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/RequirementDto.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/RequirementModReasonResponse.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/RequirementResponse.java
src/main/java/com/skala/decase/domain/requirement/controller/dto/response/SourceResponse.java
src/main/java/com/skala/decase/domain/requirement/domain/PendingRequirement.java
src/main/java/com/skala/decase/domain/requirement/domain/Reception.java
src/main/java/com/skala/decase/domain/requirement/domain/Requirement.java
src/main/java/com/skala/decase/domain/requirement/mapper/RequirementAuditMapper.java
src/main/java/com/skala/decase/domain/requirement/mapper/RequirementServiceMapper.java
src/main/java/com/skala/decase/domain/requirement/repository/RequirementAuditRepository.java
src/main/java/com/skala/decase/domain/requirement/service/ExelExportService.java
src/main/java/com/skala/decase/domain/requirement/service/PendingRequirementService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementAuditService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
src/main/java/com/skala/decase/domain/requirement/service/SrsProcessingService.java
src/main/java/com/skala/decase/global/config/WebClientConfig.java

Refactor hyo j

---

src/main/java/com/skala/decase/global/config/DBInitializer.java

fix: DBInitializer td_source로 변경

---

k8s/deploy.yaml
src/main/java/com/skala/decase/domain/document/controller/DocumentController.java
src/main/java/com/skala/decase/domain/document/mapper/DocumentMapper.java
src/main/java/com/skala/decase/domain/document/service/AsisService.java
src/main/java/com/skala/decase/domain/document/service/DocumentService.java
src/main/java/com/skala/decase/domain/mockup/controller/MockupController.java
src/main/java/com/skala/decase/domain/mockup/service/CreateMockupService.java
src/main/java/com/skala/decase/domain/mockup/service/MockupService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java
src/main/java/com/skala/decase/domain/requirement/service/SrsUpdateService.java

feat: 파일 저장 형식 변경

---

src/main/java/com/skala/decase/domain/document/service/AsisService.java
src/main/java/com/skala/decase/domain/mockup/service/MockupService.java

fix: 목업 zip 파일 다운로드 시 mockup 폴더에 png 파일 추가되는 문제

---

src/main/java/com/skala/decase/domain/member/service/MemberProjectService.java
src/main/java/com/skala/decase/domain/project/controller/dto/response/ProjectDetailResponseDto.java
src/main/java/com/skala/decase/domain/project/domain/Project.java
src/main/java/com/skala/decase/domain/project/mapper/ProjectMapper.java
src/main/java/com/skala/decase/domain/project/service/ProjectService.java
src/main/java/com/skala/decase/domain/requirement/service/RequirementService.java

fix: revision 반환하도록 수정

---

src/main/java/com/skala/decase/domain/project/service/ProjectService.java

프로젝트 리비전이 null일 경우 0으로 불러오도록 수정
